packages:
  - "."
onlyBuiltDependencies:
  - "@google/genai"
  - "@swc/core"
  - cbor-extract
  - esbuild
  - sharp
allowBuilds:
  "@google/genai": true
  "@swc/core": true
  cbor-extract: true
  esbuild: true
  sharp: true
